apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm
    repoURL: https://github.com/bmutziu/devops-toolkit.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: bmutziu/devops-toolkit
          tag: {{.IMAGE_TAG}}
        ingress:
          enabled: false
          host: devops-toolkit.54.194.74.173.xip.io
        istio:
          enabled: true
        hpa: true
        rollout:
          enabled: true
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
  - group: networking.istio.io
    kind: VirtualService
    jsonPointers:
    - /spec/http
